# Generated by Django 4.1.2 on 2022-12-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurhaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_to', models.TextField()),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TRANSIT', 'TRANSIT'), ('RECEIVED', 'RECEIVED')], default='TRANSIT', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
