# Generated by Django 4.1.2 on 2022-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purhaseorder',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
