# Generated by Django 4.1.2 on 2022-12-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
