# Generated by Django 4.1.2 on 2022-12-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item'),
        ('sales', '0004_salesorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
